// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbgS0F_4O5iFf8STb_wj-JI0SS5XMaWG0',
    appId: '1:172326065824:web:77fa3f3a094939139d1bc5',
    messagingSenderId: '172326065824',
    projectId: 'bdnew-1e932',
    authDomain: 'bdnew-1e932.firebaseapp.com',
    storageBucket: 'bdnew-1e932.firebasestorage.app',
    measurementId: 'G-QBSC1V01B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJl4yv4239rE0wEt2FeTUE0-hsvVfggK0',
    appId: '1:172326065824:android:44f89b52aa4bb8ff9d1bc5',
    messagingSenderId: '172326065824',
    projectId: 'bdnew-1e932',
    storageBucket: 'bdnew-1e932.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq_4usE1m6u4_5--9IOhAkZ9y2ad9BR5k',
    appId: '1:172326065824:ios:d1e2aa33b7fabf409d1bc5',
    messagingSenderId: '172326065824',
    projectId: 'bdnew-1e932',
    storageBucket: 'bdnew-1e932.firebasestorage.app',
    androidClientId: '172326065824-ftt0cj0u4sc5k8jhard5fqqknrnaplrf.apps.googleusercontent.com',
    iosClientId: '172326065824-e4hlt6ephp6e4lfblh4fmnk1d56mp5mr.apps.googleusercontent.com',
    iosBundleId: 'com.demo.app.uts',
  );
}
